// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using student_reg_system.database;

#nullable disable

namespace student_reg_system.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20230402164117_initial8")]
    partial class initial8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("student_reg_system.Models.Student", b =>
                {
                    b.Property<int>("StudentIDStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentIDStudent");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
