// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using student_reg_system.database;

#nullable disable

namespace student_reg_system.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("student_reg_system.Models.Student", b =>
                {
                    b.Property<int>("StudentIDStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdressStudent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateofBirthStudent")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstNameStudent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastNameStudent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentIDStudent");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
